version: "3"

services:

  conocert-api:
    image: muilpp/concerts:latest
    ports: 
      - 8282:8282
    command: >
      sh -c "cd concert-schedules && echo $LASTFM_KEY > keys/LastFMApiKey.txt
      && echo $SONGKICK_KEY > keys/SongKickApiKey.txt
      && ./concerts"
