version: "3"

services:

  conocert-api:
    image: muilpp/concerts:latest
    ports: 
      - 8282:8282
    command: >
      sh -c "cd concert-schedules
      && echo SONG_KICK_API_KEY=$SONGKICK_KEY > credentials.env
      && ./concerts"